spring.application.name=api-libreria

spring.datasource.url=jdbc:postgresql://postgres-db:5432/libreria
spring.datasource.username=postgres
spring.datasource.password=1234567
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update


