spring.application.name=api-libreria

spring.datasource.url=jdbc:postgresql://postgres-db:5432/libreria
spring.datasource.username=postgres
spring.datasource.password=1234567
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

aws.accessKey=${AWS_ACCESS_KEY}
aws.secretKey=${AWS_SECRET_KEY}
aws.region=us-east-1
aws.bucketName=bucket-uni-veritoz


